/* Finance wants to know how dependent each country is on its biggest customers.

For every country calculate:

Country Revenue
Revenue generated by the Top 10 customers
Top 10 Contribution %
Remaining Customer Revenue
Return
country
country_revenue
top10_customer_revenue
top10_contribution_pct
remaining_customer_revenue */

with cte1 as
(
select  customer_id,
        country,
        sum(sales_amount) as revenue,
        dense_rank()over( partition by country order by sum(sales_amount) desc) as rn
        from gold.fact_sales as fs
        left join gold.dim_customers as dc on fs.customer_key = dc.customer_key
        group by country, customer_id
        )
        , cte2 as
        (select country,
                sum(revenue) as country_revenue,
                sum(case when rn <= 10
                         then revenue else 0 
                         end ) as top_10_customer
                from cte1
                group by country
                )
                select country,
                       country_revenue,
                       top_10_customer,
                       round(100.0* top_10_customer/country_revenue,2) as top_10_pct,
                       (country_revenue - top_10_customer) as remainig_revenue
                       from cte2
