--Find countries where the total sales generated by the Top 2 customers exceeds 
---the average Top 2 customer sales across all countries.

with cte1 as
(
select c.country,
       o.customerid,
       sum(o.sales) as totalsales,
       row_number()over(partition by c.country order by sum(o.sales) desc) as rn
       from orders as o
       left join [sales.customers] as c
       on o.customerid = c.id
       group by c.country,o.customerid
       )
       ,cte2 as
       (
       select country,
              sum(totalsales) as avgsales
              from cte1
              where rn <=2
              group by country
              )
              select * from 
              ( select *,
                       avg(avgsales)over() as avgtotalsales
                       from cte2)t
                       where avgsales > avgtotalsales
         
