/*Country Revenue
Revenue generated by the Top 10 customers
Top 10 Contribution %
Remaining Customer Revenue
Return
country
country_revenue
top10_customer_revenue
top10_contribution_pct
remaining_customer_revenue */


with cte1 as
(
select  dc.customer_id,
        country,
        sum(sales_amount) as total_revenue,
        dense_rank()over(partition by country order by sum(sales_amount) desc) as rn
        from gold.fact_sales as fs
        left join gold.dim_customers as dc 
        on fs.customer_key = dc.customer_key
        group by dc.customer_id,
                 country
                 )
                 , cte2 as
                 (select country,
                         sum(total_revenue) as country_revenue
                         from cte1
                         group by country
                         )
                         , cte3 as
                         (select country,
                                 sum(total_revenue) as top_10_cust_revenue
                                 from cte1
                                 where rn <=10
                                 group by country
                                 )

                                 select 
                                        c2.country,
                                        country_revenue,
                                        top_10_cust_revenue,
                                        round(100.0* top_10_cust_revenue / country_revenue,2) as top_10_cust_pct,
                                        country_revenue - top_10_cust_revenue as remaining_cust_revenue
                                        from cte2 as c2
                                        join cte3 as c3
                                        on c2.country = c3.country

